FROM java:7-jre

ENV CF_HOME /opt/ColdFusion
ENV WEBROOT /var/www
ENV PATH $CF_HOME/cfusion/bin:$PATH
WORKDIR $CF_HOME

ENV ACF_LIBS_URL https://e05ac1a30afa93e642cc134035af0ab2babf7ac5.googledrive.com/host/0B-P1-Q_5RyjoMHZ2ZEtieXZjZG8/AdobeColdFusion/11/ColdFusion_exp_11_WWEJ_linux64_041514.zip

# Download and delete zip in one step to avoid committing the installer in a FS layer
RUN wget -nv $ACF_LIBS_URL -O /opt/ACF11.zip && \
	cd /opt && \
	unzip ACF11.zip && \
	rm -rf /opt/ACF11.zip

COPY ACF11/server.xml /opt/ColdFusion/cfusion/runtime/conf/

COPY ACF11/startup.sh /

EXPOSE 8500

RUN chmod 777 /startup.sh

CMD [ "/startup.sh" ]

